export const GET_USER = 'GET_USER';
export const OPEN_BILLING_FORM_DIALOG = 'OPEN_BILLING_FORM_DIALOG';
export const CLOSE_BILLING_FORM_DIALOG = 'CLOSE_BILLING_FORM_DIALOG';
export const FETCH_BILLINGS = 'FETCH_BILLINGS';
export const CREATE_BILLING = 'CREATE_BILLING';
export const DELETE_BILLING = 'DELETE_BILLING';
export const SIGN_OUT = 'SIGN_OUT';
